### PR TITLE
[FIX] Add Discriminator

### PR DESCRIPTION
**Pull request by prateekmedia**
Solves https://github.com/OpenAPITools/openapi-generator/issues/15373

### CODE REVIEW

**Comment by prateekmedia** [comment]
cc @FireMasterK, please check if this works

**Comment by FireMasterK** [comment]
Hi @prateekmedia, this PR makes the OpenAPI generator generate code with errors unfortunately, I will take a look too now.

```
lib/src/model/stream_item.g.dart:11:17: Error: The return type of the method '_$StreamItem.type' is 'String?', which does not match the return type, 'StreamItemTypeEnum?', of the overridden method, 'StreamItem.type'.
 - 'StreamItemTypeEnum' is from 'package:piped_api/src/model/stream_item.dart' ('lib/src/model/stream_item.dart').
Change to a subtype of 'StreamItemTypeEnum?'.
  final String? type;
                ^
lib/src/model/stream_item.dart:33:27: Context: This is the overridden method ('type').
  StreamItemTypeEnum? get type;
```

**Comment by FireMasterK** [comment]
We seem to have a new error now:

<details>

```
lib/src/model/stream_item.g.dart:11:17: Error: The return type of the method '_$StreamItem.type' is 'String?', which does not match the return type, 'StreamItemTypeEnum?', of the overridden method, 'StreamItem.type'.
 - 'StreamItemTypeEnum' is from 'package:piped_api/src/model/stream_item.dart' ('lib/src/model/stream_item.dart').
Change to a subtype of 'StreamItemTypeEnum?'.
  final String? type;
                ^
lib/src/model/stream_item.dart:33:27: Context: This is the overridden method ('type').
  StreamItemTypeEnum? get type;
                          ^
lib/src/model/stream_item.dart:359:44: Error: Undefined name '_$streamItemTypeEnum_stream'.
  static const StreamItemTypeEnum stream = _$streamItemTypeEnum_stream;
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/stream_item.dart:230:25: Error: A value of type 'StreamItemTypeEnum' can't be assigned to a variable of type 'String?'.
 - 'StreamItemTypeEnum' is from 'package:piped_api/src/model/stream_item.dart' ('lib/src/model/stream_item.dart').
          result.type = valueDes;
                        ^
lib/src/model/stream_item.dart:361:59: Error: Undefined name '_$streamItemTypeEnumSerializer'.
  static Serializer<StreamItemTypeEnum> get serializer => _$streamItemTypeEnumSerializer;
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/stream_item.dart:365:53: Error: Undefined name '_$streamItemTypeEnumValues'.
  static BuiltSet<StreamItemTypeEnum> get values => _$streamItemTypeEnumValues;
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/stream_item.dart:366:53: Error: Method not found: '_$streamItemTypeEnumValueOf'.
  static StreamItemTypeEnum valueOf(String name) => _$streamItemTypeEnumValueOf(name);
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/playlist_item.g.dart:9:7: Error: The non-abstract class '_$PlaylistItem' is missing implementations for these members:
 - PlaylistItem.type
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _$PlaylistItem extends PlaylistItem {
      ^^^^^^^^^^^^^^
lib/src/model/playlist_item.dart:24:29: Context: 'PlaylistItem.type' is defined here.
  PlaylistItemTypeEnum? get type;
                            ^^^^
lib/src/model/playlist_item.dart:192:48: Error: Undefined name '_$playlistItemTypeEnum_playlist'.
  static const PlaylistItemTypeEnum playlist = _$playlistItemTypeEnum_playlist;
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/playlist_item.dart:129:18: Error: The setter 'type' isn't defined for the class 'PlaylistItemBuilder'.
 - 'PlaylistItemBuilder' is from 'package:piped_api/src/model/playlist_item.dart' ('lib/src/model/playlist_item.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'type'.
          result.type = valueDes;
                 ^^^^
lib/src/model/playlist_item.dart:194:61: Error: Undefined name '_$playlistItemTypeEnumSerializer'.
  static Serializer<PlaylistItemTypeEnum> get serializer => _$playlistItemTypeEnumSerializer;
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/playlist_item.dart:198:55: Error: Undefined name '_$playlistItemTypeEnumValues'.
  static BuiltSet<PlaylistItemTypeEnum> get values => _$playlistItemTypeEnumValues;
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/playlist_item.dart:199:55: Error: Method not found: '_$playlistItemTypeEnumValueOf'.
  static PlaylistItemTypeEnum valueOf(String name) => _$playlistItemTypeEnumValueOf(name);
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/channel_item.g.dart:9:7: Error: The non-abstract class '_$ChannelItem' is missing implementations for these members:
 - ChannelItem.type
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _$ChannelItem extends ChannelItem {
      ^^^^^^^^^^^^^
lib/src/model/channel_item.dart:27:28: Context: 'ChannelItem.type' is defined here.
  ChannelItemTypeEnum? get type;
                           ^^^^
lib/src/model/channel_item.dart:249:46: Error: Undefined name '_$channelItemTypeEnum_channel'.
  static const ChannelItemTypeEnum channel = _$channelItemTypeEnum_channel;
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/channel_item.dart:165:18: Error: The setter 'type' isn't defined for the class 'ChannelItemBuilder'.
 - 'ChannelItemBuilder' is from 'package:piped_api/src/model/channel_item.dart' ('lib/src/model/channel_item.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'type'.
          result.type = valueDes;
                 ^^^^
lib/src/model/channel_item.dart:251:60: Error: Undefined name '_$channelItemTypeEnumSerializer'.
  static Serializer<ChannelItemTypeEnum> get serializer => _$channelItemTypeEnumSerializer;
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/channel_item.dart:255:54: Error: Undefined name '_$channelItemTypeEnumValues'.
  static BuiltSet<ChannelItemTypeEnum> get values => _$channelItemTypeEnumValues;
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/src/model/channel_item.dart:256:54: Error: Method not found: '_$channelItemTypeEnumValueOf'.
  static ChannelItemTypeEnum valueOf(String name) => _$channelItemTypeEnumValueOf(name);
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
package:test_core/src/runner/vm/platform.dart 255:7   VMPlatform._compileToKernel
===== asynchronous gap ===========================
package:test_core/src/runner/vm/platform.dart 232:15  VMPlatform._spawnIsolate
===== asynchronous gap ===========================
package:test_core/src/runner/vm/platform.dart 76:19   VMPlatform.load
===== asynchronous gap ===========================
package:test_core/src/runner/loader.dart 232:27       Loader.loadFile.<fn>
===== asynchronous gap ===========================
package:test_core/src/runner/load_suite.dart 99:19    new LoadSuite.<fn>.<fn>
```
</details>

**Comment by prateekmedia** [comment]
@FireMasterK I hope it will work now

**Comment by FireMasterK** [comment]
> @FireMasterK I hope it will work now

I just tried, and we get a new error:

<details>

```
Connecting to VM Service at ws://127.0.0.1:38593/K9pSOlMstDA=/ws
Failed to load "/home/kavin/Workspace/code/test/search_api_test.dart":
lib/src/model/channel_item.g.dart:9:7: Error: The non-abstract class '_$ChannelItem' is missing implementations for these members:
 - ChannelItem.type
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _$ChannelItem extends ChannelItem {
      ^^^^^^^^^^^^^
lib/src/model/channel_item.dart:26:15: Context: 'ChannelItem.type' is defined here.
  String? get type;
              ^^^^
lib/src/model/playlist_item.g.dart:9:7: Error: The non-abstract class '_$PlaylistItem' is missing implementations for these members:
 - PlaylistItem.type
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _$PlaylistItem extends PlaylistItem {
      ^^^^^^^^^^^^^^
lib/src/model/playlist_item.dart:23:15: Context: 'PlaylistItem.type' is defined here.
  String? get type;
              ^^^^
lib/src/model/channel_item.dart:163:18: Error: The setter 'type' isn't defined for the class 'ChannelItemBuilder'.
 - 'ChannelItemBuilder' is from 'package:piped_api/src/model/channel_item.dart' ('lib/src/model/channel_item.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'type'.
          result.type = valueDes;
                 ^^^^
lib/src/model/playlist_item.dart:127:18: Error: The setter 'type' isn't defined for the class 'PlaylistItemBuilder'.
 - 'PlaylistItemBuilder' is from 'package:piped_api/src/model/playlist_item.dart' ('lib/src/model/playlist_item.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'type'.
          result.type = valueDes;
                 ^^^^
package:test_core/src/runner/vm/platform.dart 255:7   VMPlatform._compileToKernel
===== asynchronous gap ===========================
package:test_core/src/runner/vm/platform.dart 232:15  VMPlatform._spawnIsolate
===== asynchronous gap ===========================
package:test_core/src/runner/vm/platform.dart 76:19   VMPlatform.load
===== asynchronous gap ===========================
package:test_core/src/runner/loader.dart 232:27       Loader.loadFile.<fn>
===== asynchronous gap ===========================
package:test_core/src/runner/load_suite.dart 99:19    new LoadSuite.<fn>.<fn>

✖ loading /home/kavin/Workspace/code/test/search_api_test.dart

Exited (1).
```
</details>

**Comment by prateekmedia** [comment]
@FireMasterK can you tell me what command are you using for generating dart?

**Comment by prateekmedia** [comment]
I tried generating code with dart-dio as the type and then ran `dart run build_runner build`, after which there were no errors.

**Comment by FireMasterK** [comment]
It looks like my flutter installation recently broke, and is hence likely the source of the issue. Will try to fix it and merge it by the day after tomorrow (I'm quite packed tomorrow unfortunately :/).

**Comment by prateekmedia** [comment]
@FireMasterK can you check?

**Comment by FireMasterK** [comment]
Seems to work now, awesome! Thanks for the help debugging! :)
Sorry about not getting back to you earlier!

**Pull request merged**
